# Netlify configuration for PropertyHub Command Frontend

[build]
  # Build command
  command = "npm run build"

  # Directory to publish (Next.js with plugin)
  publish = ".next"

  # Environment variables for build
  [build.environment]
    NODE_ENV = "production"
    NEXT_TELEMETRY_DISABLED = "1"

[build.processing]
  # Skip Netlify's processing for better performance
  skip_processing = false

[build.processing.css]
  # CSS processing
  bundle = true
  minify = true

[build.processing.js]
  # JavaScript processing
  bundle = true
  minify = true

[build.processing.html]
  # HTML processing
  pretty_urls = true

[build.processing.images]
  # Image processing
  compress = true

# Redirects and rewrites for SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    X-DNS-Prefetch-Control = "on"

[[headers]]
  for = "/static/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    # Cache JavaScript files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    # Cache CSS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    # Cache fonts for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    # Don't cache service worker
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    # Cache manifest for 1 day
    Cache-Control = "public, max-age=86400"

# Environment-specific settings
[context.production]
  command = "npm run build"
  [context.production.environment]
    NODE_ENV = "production"
    NEXT_TELEMETRY_DISABLED = "1"
    ANALYZE = "false"

[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "production"
    NEXT_TELEMETRY_DISABLED = "1"

[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "production"
    NEXT_TELEMETRY_DISABLED = "1"

# Functions configuration (if using Netlify Functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugin configuration for Next.js support
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Lighthouse plugin disabled for initial deployment
# [[plugins]]
#   package = "netlify-plugin-lighthouse"
#
#   [plugins.inputs]
#     # Lighthouse configuration
#     performance_budget = 90
#     accessibility_budget = 95
#     best_practices_budget = 90
#     seo_budget = 90

# Form handling (if needed)
[forms]
  # Enable form handling
  enabled = true

# Split testing (if needed)
[split_testing]
  # Enable split testing
  enabled = false

# Large Media (if using large assets)
[large_media]
  # Enable Large Media
  enabled = false

# Dev server configuration
[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"
  autoLaunch = false
