[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "HOSTNAME=0.0.0.0 PORT=3000 node .next/standalone/server.js"
