[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public && cd .next/standalone && HOSTNAME=0.0.0.0 PORT=3000 node server.js"
