[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = { default = "3000" }

[[services]]
name = "propertyhub-command-frontend"

[services.build]
buildCommand = "npm run build"
startCommand = "npm start"

[services.healthcheck]
path = "/"
timeout = 30

[services.variables]
# Set these in Railway dashboard
# NEXT_PUBLIC_API_URL = "https://your-backend-url.railway.app"
# NEXT_PUBLIC_WS_URL = "wss://your-backend-url.railway.app"
