# Force Nixpacks to use the Node.js provider for this service
providers = ["node"]

[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x']

[phases.install]
cmds = [
  'npm cache clean --force',
  'rm -rf node_modules package-lock.json',
  'npm install --production --no-cache --prefer-offline'
]

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = 'production'