# Force Nixpacks to use the Node.js provider for this service
providers = ["node"]

[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = ['npm run build']

[phases.start]
# Use the start command from your package.json file
cmd = "npm start"

[variables]
NODE_ENV = 'production'