[build]
builder = "NIXPACKS"
buildCommand = "npm run build:unified"

[deploy]
startCommand = "npm run start:unified"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
